### ISSUE TITLE
what about arrays in objects?

### ISSUE THREAD

**Issue by zzo** [tonybranfort/filter-objects#5]
{  zzz: [ 'a', 'b', 'c' ] }
how can I filter/match those?
zzz.0
zzz.1
zzz.2
?

**Comment by tonybranfort** [comment]
Hi Mark - filter-objects will only filter an array of non-primitive objects; eg [{a: 1}, {a: 5}, {a: 7, bar: {cat: 8}}].  It doesn't have an api for filtering an array of primitives such as strings.  You likely have already checked the javascript array.filter &/or lodash's filtering?  I'm interested if those won't work for you or if there is specific functionality that you think would be useful.
